name: On Main

on:
  push:
    branches: [ main ]

jobs:

  image_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set image version
        run: | # store the short hash for image versioning
          echo "version=$(git describe --always)" >> $GITHUB_ENV
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.14.1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        run: |
          mvn spring-boot:build-image
      - name: Push Image
        run: |
          docker tag demonstration:0.0.1-SNAPSHOT ghcr.io/bodnard/demonstration:${{ env.version }}
          docker push ghcr.io/bodnard/demonstration:${{ env.version }}

#   image_deplyoment:
#     runs-on: ubuntu-latest
#     needs: [ image_push ]
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Set up JDK 17
#         uses: actions/setup-java@v2
#         with:
#           java-version: '17'
#           distribution: 'temurin'
#           cache: maven

#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v1.14.1
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.ACTION_GITHUB_TOKEN }}

#       - name: Set k8s context
#         uses: azure/k8s-set-context@v1
#         with: # TODO update for local k8s
#           method: kubeconfig
#           kubeconfig: ${{ secrets.KUBECONFIG }}
#         id: setcontext

#       - name: Deploy
#         # https://github.com/Azure/k8s-deploy
#         uses: Azure/k8s-deploy@v1.4
#         with:
#           manifests: |
#             demonstration-deployment.yaml
#             demonstration-service.yaml
#             demonstration-ingress.yaml
#           images: "ghcr.io/bodnard/demonstration:${{ env.version }}"
#           kubectl-version: "latest"